var annotated_dup =
[
    [ "a_GPIO", "classa___g_p_i_o.html", "classa___g_p_i_o" ],
    [ "a_gpio", "classa__gpio.html", null ],
    [ "a_PWMdimmer", "classa___p_w_mdimmer.html", "classa___p_w_mdimmer" ],
    [ "Adafruit_ADS1015", "class_adafruit___a_d_s1015.html", "class_adafruit___a_d_s1015" ],
    [ "Adafruit_ADS1115", "class_adafruit___a_d_s1115.html", "class_adafruit___a_d_s1115" ],
    [ "bootflags", "structbootflags.html", "structbootflags" ],
    [ "color_ColorHSV", "structcolor___color_h_s_v.html", "structcolor___color_h_s_v" ],
    [ "color_ColorRGB", "structcolor___color_r_g_b.html", "structcolor___color_r_g_b" ],
    [ "homie_node", "classhomie__node.html", null ],
    [ "HomieDeviceDef", "struct_homie_device_def.html", "struct_homie_device_def" ],
    [ "HomieNodeDef", "struct_homie_node_def.html", "struct_homie_node_def" ],
    [ "HomiePropertyDef", "struct_homie_property_def.html", "struct_homie_property_def" ],
    [ "i_GPIO", "classi___g_p_i_o.html", "classi___g_p_i_o" ],
    [ "i_gpio", "classi__gpio.html", null ],
    [ "inicatorSampleType", "structinicator_sample_type.html", "structinicator_sample_type" ],
    [ "m_neopixel", "classm__neopixel.html", "classm__neopixel" ],
    [ "MyHomieDevice", "class_my_homie_device.html", "class_my_homie_device" ],
    [ "MyHomieNode", "class_my_homie_node.html", "class_my_homie_node" ],
    [ "MyHomieProperty", "class_my_homie_property.html", "class_my_homie_property" ],
    [ "MyLog", "class_my_log.html", "class_my_log" ],
    [ "neopixelColor", "unionneopixel_color.html", "unionneopixel_color" ],
    [ "NodeVector", "struct_node_vector.html", "struct_node_vector" ],
    [ "packedColor", "unionpacked_color.html", "unionpacked_color" ],
    [ "Plugin", "class_plugin.html", "class_plugin" ],
    [ "PropertyData", "struct_property_data.html", "struct_property_data" ],
    [ "PropertyVector", "struct_property_vector.html", "struct_property_vector" ],
    [ "s_BME680", "classs___b_m_e680.html", "classs___b_m_e680" ],
    [ "s_DUMMY", "classs___d_u_m_m_y.html", "classs___d_u_m_m_y" ],
    [ "s_HDC1080", "classs___h_d_c1080.html", "classs___h_d_c1080" ],
    [ "Sequencer", "class_sequencer.html", "class_sequencer" ],
    [ "SequenceStep", "struct_sequence_step.html", "struct_sequence_step" ],
    [ "SignalLED", "class_signal_l_e_d.html", "class_signal_l_e_d" ]
];